accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signout/', views.signout, name='signout'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password')
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/<int:comment_pk>/delete', views.comment_delete, name="comment_delete"),
]

django_fbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

boards/models.py
from django.db import models
from django.urls import reverse
# from django.contrib.auth.models import User # 사용하지 마세요
# from django.contrib.auth import get_user_model
from django.conf import settings # 가장 추천
#settings.AUTH_USER_MODEL로 쓸 것
# default 값이 'auth.User'

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    hit = models.IntegerField(default=0, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'<Board ({self.id})> : {self.title}'
        
    def get_absolute_url(self):
        return reverse('boards:detail', args=[self.pk])
        
        
class Comment(models.Model):
    comment = models.TextField()
    writer = models.CharField(max_length=10)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

boards/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Board
# class BoardForm(forms.Form):
#     title = forms.CharField(label='제목', max_length=10,
#                             error_messages={'required': '제목을 반드시 입력해주세요.'})
#     content = forms.CharField(label='내용',
#                             error_messages={'required': '내용을 반드시 입력해주세요.'},
#                             widget=forms.Textarea(attrs={
#                                     'placeholder': '내용을 입력해줘!',
#                                     'class': 'input-box'  
#                                     })
#                             )

# modelform
class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        # fields = ['title', 'content']
        fields = ['title', 'content']
    #     widgets = {'title': forms.TextInput(attrs={
    #                                         'placeholder':'제목을 입력해주세요.',
    #                                         'class': 'title'}),
    #                 'content': forms.Textarea(attrs={
    #                                         'placeholder': '내용을 입력해주세요.',
    #                                         'class': 'content'})
    #                 }
    #     error_messages = {'title': {
    #                                 'required': '제목을 반드시 입력해주세요.'
    #                         },
    #                         'content': {
    #                                 'required': '내용을 반드시 입력해주세요.'
    #                         }
    #                     }
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.form_method = 'POST'
    #     self.helper.add_input(Submit('submit', 'Submit'))
            
                

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Board, Comment
from .forms import BoardForm
# Create your views here.
# @login_required
def index(request):
    boards = Board.objects.order_by('-pk')
    context = {'boards': boards}
    return render(request, 'boards/index.html', context)

@login_required
def create(request):
    # if not request.user.is_authenticated:
    #     return redirect('boards:index')
    if request.method == 'POST':
        board_form = BoardForm(request.POST)
        if board_form.is_valid():
            # title = board_form.cleaned_data.get('title')
            # content = board_form.cleaned_data.get('content')
            # board = Board(title=title, content=content)
            # board.user = request.user
            # board.save()
            board = board_form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect(board)
    else:
        board_form = BoardForm()
    context = {'board_form': board_form}
    return render(request, 'boards/form.html', context)
    
def detail(request, board_pk):
    # board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == "POST":
        comment = Comment(comment=request.POST.get('comment'), writer=request.user, board_id=board_pk)
        comment.save()
        return redirect('boards:detail', board_pk)
    else:
        board.hit += 1
        board.save()
    comments = board.comment_set.all()
    context = {'board': board, 'comments': comments}
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect(board)

def comment_delete(request, board_pk, comment_pk):
    board = Board.objects.get(pk=board_pk)
    comment = board.comment_set.get(pk=comment_pk)
    comment.delete()
    return redirect('boards:detail', board_pk)

def update(request, board_pk):
    # 1. board_pk에 해당하는 오브젝트를 가져온다.
    #    - 없으면, 404 에러.
    #    - 있으면, board = Board.objects.get(pk=board_pk) 와 동일.
    board = get_object_or_404(Board, pk=board_pk)
    # 2-1. POST 요청이면 (사용자가 form을 통해 데이터를 보내 준 것.)
    if request.method == 'POST':
        # 사용자 입력값(request.POST)을 BoardForm에 전달해주고,
        board_form = BoardForm(request.POST, instance=board)
        # 검증 (유효성 체크)
        if board_form.is_valid():
            # board.title = board_form.cleaned_data.get('title')
            # board.content = board_form.cleaned_data.get('content')
            # board.save()
            board = board_form.save()
            return redirect(board)
    # 2-2. GET 요청이면 (수정하기 버튼을 눌렀을 때)
    else:
        # BoardForm을 초기화(사용자 입력값을 넣어준 상태)
        board_form = BoardForm(instance=board) 
    # context에 담겨있는 board_form은 두가지 상황이 있다.
    # 1 - POST 요청에서 검증에 실패하였을 때, 오류 메세지가 포함된 상태
    # 2 - GET 요청에서 초기화된 상태
    context = {'board_form': board_form}
    return render(request, 'boards/form.html', context)

boards/templates/boards/base.html
{% load static %}
{% load gravatar %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FBV</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% if messages %}
    <!--<ul class="messages">-->
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    <!--</ul>-->
    {% endif %}
    <div class="container my-3">
        <div class="row">
            {% if user.is_authenticated %}
            <div class="col-4 item-aligns">
                <img src="https://s.gravatar.com/avatar/{{ user.email|makehash }}?s=150&d=https://stickershop.line-scdn.net/stickershop/v1/product/8542/LINEStorePC/main.png;compress=true">
            </div>
            <div class="col-8">
                <h1 class="mx-3">{{ user }}님 환영합니다 :)</h1>
                <a href="{% url 'accounts:logout' %}">로그아웃</a>
                <a href="{% url 'accounts:update' %}">프로필 수정</a>
            </div>
            <br>
            {% else %}
            <a href="{% url 'accounts:signup' %}">회원가입</a>
            <a href="{% url 'accounts:login' %}">로그인</a>
            {% endif %}
        </div>
        {% block body %}
        {% endblock %}
        <hr>
        <form action="{% url 'accounts:signout' %}" method="POST" onsubmit="return confirm('탈퇴하시겠습니까?')">
            {% csrf_token %}
            <input type="submit" value="회원탈퇴" class="btn btn-outline-warning">
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

boards/templates/boards/create.html
{% extends 'boards/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ board_form.as_p }}
    <input type="submit">
</form>
{% endblock %}

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
<div class="container my-3">
    <h5>{{ board.pk }}번째 글</h5>
    <h1>{{ board.title }}</h1>
    <h4>{{ board.user }}</h4>
    <b>조회수 : {{ board.hit }}</b>
    <hr>
    <p style="font-size: large">{{ board.content }}</p>
    <hr>
    <p class="badge badge-pill badge-info" style="font-size: large">comments</p>
    <br>
    {% for comment in comments %}
        <p class="d-inline">{{ comment.writer }} : {{ comment.comment }}</p>
        <a href="{% url 'boards:comment_delete' board.pk comment.pk %}" class="badge badge-primary d-inline">삭제</a>
        <br>
    {% empty %}
        <b>댓글이 없어요 ㅠ.ㅠ</b>
    {% endfor %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <span>내용</span> <input type="text" class="form-control d-inline" name="comment">
        </div>
        <input type="submit" value="댓글작성" class="btn btn-primary">
    </form>
</div>
{% if board.user == request.user or request.user.is_superuser %}
    <form action="{% url 'boards:delete' board.pk %}" method="POST" style="display: inline; height: 5px;">
        {% csrf_token %}
        <input type="submit" value="게시글 삭제" class="btn btn-outline-primary">
    </form>
{% endif %}
<a href="{% url 'boards:update' board.pk %}" class="btn btn-outline-primary d-inline">게시글 수정</a>
{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>새글 작성</h1>
{% else %}
    <h1>글 수정</h1>
{% endif %}
{# crispy board_form #}
<form method="POST">
    {% csrf_token %}
    {{ board_form|crispy }}
    <input type="submit">
</form>

<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    <div class="row">-->
<!--        {% for field in board_form %}-->
<!--            <div class="col-6">-->
<!--                {{ field.errors }}-->
<!--                {{ field.label_tag }} {{ field }}-->
<!--            </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--</form>-->

<!--<form method="POST">-->
<!--    <div class="row">-->
<!--        <div class="col-2">-->
<!--            {{ board_form.title }}-->
<!--        </div>-->
<!--        <div class="col-10">-->
<!--            {{ board_form.content }}-->
<!--        </div>-->
<!--    </div>-->
<!--</form>-->
{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body %}
<h1>게시글 목록</h1>
{% if user.is_authenticated %}
    <a href="{% url 'boards:create' %}">글 쓰러가기</a>
{% endif %}
{% for board in boards %}
    <div class="card">
        <div class="card-header">board {{ board.pk }}</div>
        <div class="card-body">
            <h5 class="card-title">{{ board.title }}</h5>
            <p class="card-text">{{ board.content }}</p>
            <a href="{% url 'boards:detail' board.pk %}" class="btn btn-outline-info">글 보러가기</a>
        </div>
    </div>
    <hr>
{% endfor %}
{% endblock %}