accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signout/', views.signout, name='signout'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password')
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/<int:comment_pk>/delete', views.comment_delete, name="comment_delete"),
]

django_fbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model # User class 를 가지고 옴
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

# class UserForm(forms.ModelForm):
#     class Meta:
#         model = get_user_model()
#         # fields = '__all__'
#         fields = ['username', 'password']
class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email')


class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

accounts/views.py
from django.shortcuts import render, redirect
# from .forms import UserForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth import login as auth_login # 재귀로 호출되지 않도록 하기 위해 auth_login으로 변경
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_http_methods

from .forms import UserCustomChangeForm, UserCustomCreationForm

# Create your views here.
def index(request):
    users = get_user_model().objects.all()
    context = {'users': users}
    return render(request, 'accounts/index.html', context)

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    boards = user.board_set.all()
    context = {'user': user, 'boards': boards}
    return render(request, 'accounts/detail.html', context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            messages.info(request, f'{user.username}님, 회원가입 성공!')
            return redirect('boards:index')
        messages.warning(request, '양식을 다시 확인해주세요.')
    else:
        user_form = UserCustomCreationForm()
    context = {'user_form': user_form}
    return render(request, 'accounts/signup.html', context)
    
def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST) # 사용자의 쿠키 값을 받아오기 위해 request 인자를 추가, 사용자가 입력한 정보 + 서버에서 가져온 값을 비교
        if login_form.is_valid():
            auth_login(request, login_form.get_user()) # form에서 사용자와 관련된 정보만을 뽑아서 session을 만드는 함수
            return redirect('boards:index')
    else:
        login_form = AuthenticationForm()
    context = {'login_form': login_form}
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('boards:index')
    
@login_required
def signout(request):
    if request.method == 'POST':
        request.user.delete()
    return redirect('boards:index')
    
# @login_required
# @require_http_methods(["POST"]) # method가 없음을 나타내는 405코드를 보냄, 성공 시에는 200코드
# def signout(request):
#     request.user.delete()
#     return redirect('boards:index')


def update(request):
    # user_form = UserChangeForm()
    if request.method == 'POST':
        user_form = UserCustomChangeForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect('boards:index')
    else:
        user_form = UserCustomChangeForm(instance=request.user)
    context = {'user_form':user_form}
    return render(request, 'accounts/update.html', context)
    
@login_required
def password(request):
    if request.method == 'POST':
        user_form = PasswordChangeForm(request.user, request.POST) # 순서 주의!
        if user_form.is_valid():
            user_form.save()
            update_session_auth_hash(request, user)
        return redirect('boards:index')
    else:
        user_form = PasswordChangeForm(request.user) # instance = 아님을 주의!
    context = {'user_form': user_form}
    return render(request, 'accounts/update.html', context)

accounts/templates/accounts/detail.html
{% load gravatar %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <img src="https://s.gravatar.com/avatar/{{ user.email|makehash }}?s=150&d=https://stickershop.line-scdn.net/stickershop/v1/product/8542/LINEStorePC/main.png;compress=true">
    <p>email : {{ user.email }}</p>
    <p>username : {{ user }}</p>
    <ul>
    {% for board in boards %}
        <li>{{ board.title }}</li>
    {% endfor %}
    </ul>
</body>
</html>

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>user list</h1>
    {% for user in users %}
        <a href="{% url 'accounts:detail' user.pk %}"><h4 style='display: inline'>{{ user }}</h4></a>
        <br>   
   {% endfor %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<form method='POST'>
    {% csrf_token %}
    {{ login_form|crispy }}
    <input type='submit' value='로그인'>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<form method='POST'>
    {% csrf_token %}
    {{ user_form|crispy }}
    <input type='submit' value='회원가입 신청'>
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<form method='POST'>
    {% csrf_token %}
    {{ user_form|crispy }}
    <input type='submit' value='프로필 수정'>
</form>
{% endblock %}